### PR TITLE
Adds `fix_root_link` attribute to ArticulationRootPropertiesCfg 

### LINKED ISSUE #365: [Question] How to fix base link?
Hi, Thank you for the nice work,

Main question: How to fix the base link of robot arm on the ground? 

I am using Techman tm5-900 with Tesollo delto-gripper (DG3F) generated by URDF Importer2usd.
When I imported the robot's URDF, unchecked the "Fix Base Link" button as an import option because It couldn't generate multiple environments (can generate but all robots are fixed to the base link) in RLTaskEnv.

Is there any solution or document that I refer to in python as pose processing? 

Thank you already.

(You can check the situation.)
q1

### PR DESCRIPTION
**Pull request by Mayankm96**
# Description

This MR adds an attribute to fix the root link of an articulation. It also fixes the docstrings to mention how to fix a rigid body in the scene.

Fixes #365, #181

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./orbit.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run all the tests with `./orbit.sh --test` and they pass
- [x] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already exists there

### CODE REVIEW

**Comment by Mayankm96** [comment]
@Dhoeller19 @jsmith-bdai The test currently doesn't work for articulation. Will debug it later next week.

**Comment by Mayankm96** [comment]
Everything works now!

**Comment by Mayankm96** [comment]
Solved in 2ae4b2d8a75bb177815aafc1d839402e3b5816e1

**Comment by cjoattesollo** [comment]
> Solved in [2ae4b2d](https://github.com/NVIDIA-Omniverse/orbit/commit/2ae4b2d8a75bb177815aafc1d839402e3b5816e1)

@Mayankm96 Working well in my envs. Thanks!

**Comment by john2choi** [comment]
> Solved in [2ae4b2d](https://github.com/NVIDIA-Omniverse/orbit/commit/2ae4b2d8a75bb177815aafc1d839402e3b5816e1)

@Mayankm96 Working well in my envs. Thanks!

**Pull request closed without merging**
