### PR TITLE
Updates robomimic config for Franka-Lift environment

### LINKED ISSUE #68: [Bug Report] Mismatch in the observations between data collection and training in robomimic example workflow
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

When running the agent training step of the [Robomimic example](https://isaac-orbit.github.io/orbit/source/setup/sample.html#imitation-learning) following the documentation. I get an error saying that object 'object_positions' doesn't exist

### Steps to reproduce

Just follow the exact steps in [`Running existing scripts/Imitation Learning`](https://isaac-orbit.github.io/orbit/source/setup/sample.html#imitation-learning) in the document page.

```bash
# step a: collect data with keyboard
./orbit.sh -p source/standalone/workflows/robomimic/collect_demonstrations.py --task Isaac-Lift-Franka-v0 --num_envs 1 --num_demos 10 --device keyboard

# split data
./orbit.sh -p source/standalone//workflows/robomimic/tools/split_train_val.py logs/robomimic/Isaac-Lift-Franka-v0/hdf_dataset.hdf5 --ratio 0.2

./orbit.sh -p source/standalone/workflows/robomimic/train.py --task Isaac-Lift-Franka-v0 --algo bc --dataset logs/robomimic/Isaac-Lift-Franka-v0/hdf_dataset.hdf5
```

### System Info

Describe the characteristic of your environment:

- Commit: 9d27e4dc0009d72667f482c21dd070d4d9f95c22
- Isaac Sim Version: 2022.2.1-rc.14+2022.2.494.70497c06.tc
- OS: Ubuntu 20.04
- GPU: NVIDIA GeForce RTX 3080 Ti
- CUDA: 12.0
- GPU Driver: 525.105.17

### Additional context

I think the problem is that in `lift_bc.json` there is `object_positions`, whereas in `lift_cfg.py` it is commented out. There is `object_relative_tool_positions` instead.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### PR DESCRIPTION
**Pull request by yangcyself**
# Description

1. Enlarge the hard-coded success range from 0.002 to 0.02 so that it's possible for a human operator to succeed.
2. Update from `object_positions` to `object_relative_tool_positions` in [lift_bc.json](https://github.com/NVIDIA-Omniverse/Orbit/compare/main...yangcyself:Orbit:bugfix-68-mismatch-robomimic?expand=1#diff-9c052c38b3652ed4763c9e269b8a86c8b92c8689c0cd8afa58ca35e4c0dc605d) and [lift_bcq.json](https://github.com/NVIDIA-Omniverse/Orbit/compare/main...yangcyself:Orbit:bugfix-68-mismatch-robomimic?expand=1#diff-a6baabb6e1118ad88d5baff9048773db5899673d44a4831d03db613f7e020a00), to match with the configuration in [lift_cfg.py](https://github.com/NVIDIA-Omniverse/orbit/blob/6e6fa68e778d725d489a64068602e7c09d0b019e/source/extensions/omni.isaac.orbit_envs/omni/isaac/orbit_envs/manipulation/lift/lift_cfg.py)

Fixes #68 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `./orbit.sh --format`
- [ ] I have made corresponding changes to the documentation: Not applicable
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works: Not applicable
- [ ] I have updated the changelog and the corresponding version in the extension's `config/extension.toml` file: Not applicable

### CODE REVIEW

**Comment by Mayankm96** [comment]
Are you able to train a policy through imitation learning with these changes?

I think in the earlier version, object_positions were the object pose in the environment frame, not relative to tool frame.

**Comment by yangcyself** [comment]
I actually did not succeed in training a policy to grab the tube with behavior cloning. But I thought it was because of the bad demonstrations I provided. 

And yes, in the earlier version `object_positions` was used in `lift_cfg.py` but you changed it to `object_relative_tool_positions` in #33 ([link](https://github.com/NVIDIA-Omniverse/Orbit/pull/33/files#diff-584c1d9279b2e1dfd0f79f8c1751e1b96583a9a9fdf5380d61c199d5bad89c29)), so I thought we need to update and use `object_relative_tool_positions` in imitation learning.

So maybe it's better to stick to the previous setting and use `object_positions`? So what I should do it's to config the observation to collect `object_positions` in the data collection step, by changing the file `collect_demonstrations.py`?

**Comment by Mayankm96** [comment]
Training with human data can indeed be challenging. I recommend checking this paper on tips for imitation learning
> https://arxiv.org/abs/2108.03298

Maybe to check if the observations make sense, you can collect data with the state machine and see how it performs. It would be easier to collect data that way.

**Review by Mayankm96 — APPROVED** [review]
Looks good. Would need to attempt re-training again but will do that when the time comes.

**Pull request merged**
